Achievement description cleanup
Kinglink/RAScripts pull request #8
Opened 2024-12-02 16:38 UTC by Argenrost

Wanted to start by saying I really appreciate the work you put into this, vanilla DW3 was also a big part of my younger years and continues to influence my love for the series to this day.

I don't have the time or the know-how just yet to contribute actual achievements, but I wanted to propose some small updates to the titles and descriptions if possible. A lot of these changes are just minor bits of text and punctuation cleanup, but there was also a small error where the achievements for clearing 7-stage and 10-stage Musou Modes were given the wrong set of caveats in their descriptions (7-stage Musou Modes were listed as leader required, 10-stage were non-leader).

Cheers!

2024-12-03 04:30 UTC, Kinglink requested changes
Excellent changes, please fix the punctuation.

2024-12-03 04:30 UTC, Kinglink commented on Dynasty_Warriors_3_Playstation_2/Dynasty_Warriors_3.rascript
> +asASinglePlayerString = " as a single player."
Can you please remove the punctuation changes (At least the periods at the end of Descriptions).  I appreciate the thought, but it's not required (as long as it's uniformed) and not prefered. 

Reference:
https://docs.retroachievements.org/guidelines/content/writing-policy.html#punctuation-1

2024-12-03 04:30 UTC, Kinglink commented on Dynasty_Warriors_3_Playstation_2/Dynasty_Warriors_3.rascript
> +            "Defeat exactly 7 officers as Meng Huo during The Nanman Campaign with the Nanman Forces"  + asASinglePlayerString + " (Kills must be done by the player, bodyguard and other kills will no
Good catch.

2024-12-03 04:36 UTC, Kinglink approved these changes
This commit looks fine.

2024-12-03 04:36 UTC, Kinglink requested changes
This commit looks fine. (Though please revert the other punctuation changes.

2024-12-03 06:07 UTC, Argenrost reviewed
Updated in accordance with the punctuation guidelines. I tried to remove as many periods as possible while keeping it looking clean; if descriptions shouldn't be ended with periods I'd rather avoid them entirely to keep it from looking awkward.

2024-12-03 06:07 UTC, Argenrost commented on Dynasty_Warriors_3_Playstation_2/Dynasty_Warriors_3.rascript
> +asASinglePlayerString = " as a single player."
Done, feel free to look it back over and see if I missed anything.

2024-12-03 07:06 UTC, Argenrost reviewed
I did a second pass out of curiosity and noticed I missed a few of the added periods. I also took the opportunity to clean up some more of the formatting, including removing the potential for extra spaces.

2024-12-03 14:52 UTC, Argenrost reviewed
Done.

2024-12-09 01:00 UTC, Kinglink approved these changes

2024-12-09 01:47 UTC, merged